services:
  training:
    build:
      context: ./docker
    image: koduj.dev/ts-sandbox:latest
    container_name: ts-sandbox
    volumes:
      - ./sandbox:/app/sandbox
      - ./work:/app/work
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "12000:3000"
    networks:
      - koduj-dev

networks:
  koduj-dev:
    name: koduj-dev
    driver: bridge